### ISSUE TITLE
Include Rondo Classic radio channels

### ISSUE THREAD

**Issue by gitarra** [Jollailija/nettiradio#1]
Rondo Classic serves 2 Finnish internet radio channels (Klasu and Klasu Pro) that are not included with the application.

You can find the stream addresses in here:

http://www.rondoclassic.fi/nettiradio-ohjeet

**Comment by Jollailija** [comment]
Terve! Thank you for your feedback. I added the channels (plus Viva Classica) to the station list, they will be included in the next update. In case you don't want to wait, I uploaded 1.0.4 release 2 to OpenRepos which includes these stations. You can install it right now from https://openrepos.net/content/jollailija/finnish-net-radio-client-beta

**Comment by gitarra** [comment]
Kiitos :+1:
