### ISSUE TITLE
Hitmix has replaced Metro Helsinki

### ISSUE THREAD

**Issue by Yellow-Me** [Jollailija/nettiradio#3]
New nationwide channel Hitmix has replaced Metro Helsinki. Stream address is same as before, so only the name and the coverage area need to updated on the channel list.

**Comment by Jollailija** [comment]
Fixed in 83dd05a. Many thanks for reporting and sorry for the delay!

**Comment by Jollailija** [comment]
Yeah, I totally know how GitHub issues work :D
